vendor: KBSYS Inc.
name: BizKube
version: 1.1
website_url: http://www.bizkube.co.kr
documentation_url: https://www.kb-sys.co.kr/fileUpload/BizKube.html
product_logo_url: https://www.kb-sys.co.kr/fileUpload/bizkube.svg
type: distribution
description: 'Bizkube is a next-generation enterprise distributed processing and hybrid cloud operating solution that provides Built, Deployment, Elastic Scaling Modern Applications, and Data Service capabilities, various open source support, and a customized docker environment for users.'
contact_email_address: jhsong@kb-sys.co.kr