vendor: QBO LLC
name: qbo-ce
version: ce-prod-4.3.2-0cb9f5f4f
website_url: https://ce.qbo.io
repo_url: https://github.com/alexeadem/qbo-ce
documentation_url: https://ce.qbo.io
product_logo_url: https://raw.githubusercontent.com/alexeadem/qbo-ce/main/docs/img/qbo_250x150.svg
type: distribution
description: "Qbo stands out as the exclusive AsyncAPI leveraging Docker in Docker (DinD) technology, dedicated to deploying and managing AI workloads in Kubernetes with unmatched metal performance. Unlocking the power of cloud computing for anyone, anywhere."
contact_email_address: info@qbo.io
