vendor: KBSYS Inc.
name: Bizmicro-Portal
version: 1.0
website_url: https://www.bizmicro.co.kr
documentation_url: https://www.bizmicro.co.kr/en/product-bizmicro.html
product_logo_url: https://www.kb-sys.co.kr/fileUpload/bizmicro.svg
type: hosted platform
description: Kubernetes-based SaaS platform includes tools related to OAuth-based authentication, CDN-based file management, CI/CD pipeline placement management, API management, monitoring, and site Reliability engineering (SRE). This makes it easy to configure cloud-native applications optimized for public, on-premises, and hybrid clouds.
contact_email_address: jhsong@kb-sys.co.kr