vendor: Navimentum Information System Co., Ltd.
name: Navimentum K8M PaaS
version: V2023.12
website_url: https://www.navimentum.com
documentation_url: https://www.navimentum.com/nv/product/detail/1258262267811549186
product_logo_url: https://landscape.cncf.io/logos/navimentum-kcsp.svg
type: distribution
description: 'K8M is a production level PaaS platform that can be used for enterprise and internet application deployment and management.'
contact_email_address: zhaoqg@navimentum.com
